:websocket-link: http://www.hivemq.com/demos/websocket-client/

== Delete Retained Messages Recursively Plugin

=== Purpose

The Delete Retained Messages Recursively Plugin is just a small example plugin, meant to demonstrate the functionality of the Retained Message Store.
It enables a client to delete the retained message of a topic and the retained messages of all it's subtopic at once.

=== How to use the plugin

Usually a retained message is removed, by publishing a new retained message with an empty payload to the topic of the retained message that should be deleted.
As long as this plugin is installed, the retained messages of all subtopics will be removed as well.

=== Example

. Copy the plugin into the plugins directory of you HiveMQ
. Run HiveMQ
. Connect a client (you could use the {websocket-link}[HiveMQ Websocket Client] for this purpose.
. Publish a retained message with a not empty payload to the topic "test"
. Publish an other retained message with a not empty payload to the topic "test/a"
. Publish an empty retained message to "test"
. Both retained messages should be removed

= Contributing

If you want to contribute to HiveMQ Delete Retained Messages Recursively Plugin, see the link:CONTRIBUTING.md[contribution guidelines].

= License

HiveMQ Delete Retained Messages Recursively Plugin is licensed under the `APACHE LICENSE, VERSION 2.0`. A copy of the license can be found link:LICENSE.txt[here].
